//
//  WalletInteractor.swift
//  EthereumWallet
//
//  Created by Sharon Varghese on 25/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletBusinessLogic
{
    func fetchWalletDetails()
}

protocol WalletDataStore
{
  //var name: String { get set }
}

class WalletInteractor: WalletBusinessLogic, WalletDataStore
{
  var presenter: WalletPresentationLogic?
  var worker = WalletWorker()
  //var name: String = ""
  
  // MARK: Do something
    
    func fetchWalletDetails() {
        
        worker.fetchTransactionsCount(walletAddress: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045") { result in
            switch result {
            case .success(let success):
                print("transactioncount === \(success)")
            case .failure(let failure):
                print(failure)
            }
        }
        
        worker.fetchWalletBalance(walletAddress: "0xd8da6bf26964af9d7eed9e03e53415d37aa96045") { result in
            switch result {
            case .success(let success):
                print(success)
            case .failure(let failure):
                print(failure)
            }
        }
        
        worker.fetchWalletAddress { result in
            switch result {
            case .success(let success):
                print(success)
            case .failure(let failure):
                print(failure)
            }
        }
    }
    
  

  
 
}
